Add s2s secret
hmcts/rd-profile-sync pull request #463
Opened 2021-02-02 13:17 UTC by vijayrajagopalan-hmcts

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RDCC-2067

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2021-02-02 13:40 UTC, AdilOoze approved these changes

2021-02-02 13:52 UTC, shreedhar-hmcts approved these changes
just monitor aat and prd pods after merge

2021-02-02 14:31 UTC, nitishsingla1234 approved these changes

2021-02-02 16:45 UTC, AdilOoze approved these changes

2021-02-02 16:52 UTC, ConorH994 approved these changes

2021-02-02 16:58 UTC, shreedhar-hmcts requested changes
Just do it tomorrow

2021-02-03 09:31 UTC, shreedhar-hmcts approved these changes

2021-02-03 11:20 UTC, merged