RDCC-3782: Collating dependabot PRs
hmcts/rd-profile-sync pull request #569
Opened 2021-12-20 15:05 UTC by AdilOoze

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RDCC-3782

### Change description ###

Collating Dependabot PRs

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-12-20 16:32 UTC, SujeethKumarAri requested changes
Approved but blocking to avoid accidental merge

2022-01-05 14:06 UTC, sahitya-desireddy submitted a review, later dismissed

2022-01-05 14:09 UTC, SujeethKumarAri requested changes

2022-01-05 14:09 UTC, SujeethKumarAri commented on Jenkinsfile_nightly
> +    enableFortifyScan()
We need not do these changes now. Sorry mate

2022-01-05 14:09 UTC, SujeethKumarAri commented on Jenkinsfile_nightly
We need not do these changes now. Sorry mate

2022-01-05 14:15 UTC, sahitya-desireddy approved these changes

2022-01-05 14:54 UTC, merged