DTSRD-85: Update Profile Sync to Spring Boot 3
hmcts/rd-profile-sync pull request #742
Opened 2023-10-19 13:44 UTC by kiran-yenigala-hmcts

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/DTSRD-85

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2023-10-19 15:10 UTC, lukasz-wolski submitted a review, later dismissed

2023-10-19 15:15 UTC, SabinaHMCTS submitted a review, later dismissed

2023-10-23 09:36 UTC, rajkatla-hmcts approved these changes

2024-07-17 08:15 UTC, lukasz-wolski approved these changes

2024-07-17 09:14 UTC, rajkatla-hmcts approved these changes

2024-07-18 08:57 UTC, lukasz-wolski commented on build.gradle
> +	implementation ('com.github.hmcts:properties-volume-spring-boot-starter:0.1.1'){
library is now deprecated and needs to be removed

2024-07-18 08:59 UTC, lukasz-wolski requested changes
remove deprecated lib, please see comment inlined

2024-07-18 09:21 UTC, lukasz-wolski approved these changes

2024-07-18 09:56 UTC, rajkatla-hmcts approved these changes

2024-07-18 10:03 UTC, merged